# This file was generated by GoReleaser. DO NOT EDIT.
cask "runnerkit" do
  version "1.0.7"

  on_macos do
    on_intel do
      sha256 "4753efe4c87987ac9bd5144c4e306cab8bdc83b9117af04fb333b8c6f15f6e45"
      url "https://github.com/accidentally-awesome-labs/runnerkit/releases/download/v#{version}/runnerkit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a0334f05306542466b3cf45589eec4481cc101b2682fd729a916b46272718c9"
      url "https://github.com/accidentally-awesome-labs/runnerkit/releases/download/v#{version}/runnerkit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2868fb82359b7d91d0efc108f0bcfde299c8bb6d6224d4d96aa7329a15170ee1"
      url "https://github.com/accidentally-awesome-labs/runnerkit/releases/download/v#{version}/runnerkit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fbd6c6066d0bc08995cb90bff40b49c2e752f56c51b01f3239b8df47e386cf6b"
      url "https://github.com/accidentally-awesome-labs/runnerkit/releases/download/v#{version}/runnerkit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "runnerkit"
  desc "Reliable GitHub Actions self-hosted runners for solo developers"
  homepage "https://github.com/accidentally-awesome-labs/runnerkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runnerkit"

  # No zap stanza required

end
