# This file was generated by GoReleaser. DO NOT EDIT.
cask "runnerkit" do
  version "1.0.6"

  on_macos do
    on_intel do
      sha256 "370fb6a6357338d41dc9193c9d4f7dd00df7a5e54d6523c122a1e5b8ef779921"
      url "https://github.com/accidentally-awesome-labs/runnerkit/releases/download/v#{version}/runnerkit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "daea1419a06bcd376bcf1ae0962814adb3e8df47aec9704a59899d530d28e703"
      url "https://github.com/accidentally-awesome-labs/runnerkit/releases/download/v#{version}/runnerkit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4ade47167a606c4da081f936e846f96617bc06fea8e89db3cd28dce4c17962fc"
      url "https://github.com/accidentally-awesome-labs/runnerkit/releases/download/v#{version}/runnerkit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "77edebe5b4239956fb188d432e11a7ada21ff36e33f35603bd1e82b65ab548b6"
      url "https://github.com/accidentally-awesome-labs/runnerkit/releases/download/v#{version}/runnerkit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "runnerkit"
  desc "Reliable GitHub Actions self-hosted runners for solo developers"
  homepage "https://github.com/accidentally-awesome-labs/runnerkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runnerkit"

  # No zap stanza required

end
