# This file was generated by GoReleaser. DO NOT EDIT.
cask "runnerkit" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "f3397f1eadbcd1dc7455adfaaf42dc9644e012f761bb5a378e9dc49419fa6d64"
      url "https://github.com/accidentally-awesome-labs/runnerkit/releases/download/v#{version}/runnerkit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0a134d4fcff349f199844470e01e22ce02088f14944ef62be58869547127b6e6"
      url "https://github.com/accidentally-awesome-labs/runnerkit/releases/download/v#{version}/runnerkit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dbda95ef9e3db9c40ce5f8fe023d56a41cc95178590db34b756af5d56f20bf97"
      url "https://github.com/accidentally-awesome-labs/runnerkit/releases/download/v#{version}/runnerkit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8252751810319bc5d5779e5339e20cc2e7b916be916e160cd96ae31afbb8202"
      url "https://github.com/accidentally-awesome-labs/runnerkit/releases/download/v#{version}/runnerkit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "runnerkit"
  desc "Reliable GitHub Actions self-hosted runners for solo developers"
  homepage "https://github.com/accidentally-awesome-labs/runnerkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runnerkit"

  # No zap stanza required

end
